#ifndef INPUT_FHETRIGGERTYPE_H_
#define INPUT_FHETRIGGERTYPE_H_

enum FHETriggerType
{
	FHE_TRIGGER_TYPE_RELEASED = GLFW_RELEASE,
	FHE_TRIGGER_TYPE_PRESSED = GLFW_PRESS,
	FHE_TRIGGER_TYPE_HELD,
};

#endif
